services:
  db:
    restart: always
    image: postgres:15
    env_file:
      - ../.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      depends_on:
        - db
      env_file:
      - ../.env
      ports:
        - "5051:80"
      restart: always

  web:
    build:
      context: ../
      dockerfile: .docker-debug/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../:/code
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: