# Generated by Django 4.2.13 on 2024-05-28 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NAME')),
                ('rate', models.PositiveIntegerField(verbose_name='RATE')),
                ('password', models.CharField(max_length=255, verbose_name='PASSWORD')),
                ('first_player', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first', to=settings.AUTH_USER_MODEL)),
                ('second_player', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
