# Generated by Django 4.2.13 on 2024-05-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='PASSWORD'),
        ),
    ]
