services:
  db:
    restart: always
    image: postgres:15
    env_file:
      - ../.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    env_file:
    - ../.env
    ports:
      - "5051:5050"
    restart: always

  web:
    build:
      context: ../
      dockerfile: .docker-prod/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../:/code
    command: uvicorn myproject.asgi:application --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - staticfiles:/code/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
    
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_volume_data:/data

volumes:
  staticfiles:
  postgres_data:
  redis_volume_data: